version: '3'
services:
  nginx:
   container_name: docker-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - app
 
  mysql:
   container_name: docker-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: seminar
    MYSQL_ROOT_PASSWORD: password
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3306:3306"
   restart: always
  
  app:
    restart: always
    build: ./seminar-web
    working_dir: /seminar-web
    volumes:
      - ./seminar-web:/seminar-web
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql
